"""Markdown-ish memo → PDF via fpdf2.

Light/cream paper with gold accents, dark serif body. Sanitizes unicode that
isn't in the latin-1 charset used by the built-in PDF fonts.
"""

from __future__ import annotations

import re
from datetime import datetime
from zoneinfo import ZoneInfo

from fpdf import FPDF

GOLD = (201, 168, 76)
DARK = (28, 28, 28)
MUTED = (110, 110, 110)
RULE = (210, 200, 170)
PAPER = (253, 251, 243)


_UNI_MAP = {
    "·": " - ", "—": " -- ", "–": "-", "…": "...",
    "“": '"', "”": '"', "‘": "'", "’": "'",
    "→": "->", "←": "<-", "⇒": "=>",
    "◆": "*", "◈": "*", "•": "*", "●": "*",
    "⬇": "v", "⚠": "!", "§": "S",
    "₹": "Rs", "€": "EUR", "£": "GBP", "¥": "JPY",
    " ": " ",
}


def _sanitize(text: str) -> str:
    for k, v in _UNI_MAP.items():
        text = text.replace(k, v)
    # Strip inline bold/italic/code markers — fpdf doesn't do inline styling cleanly
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)", r"\1", text)
    text = re.sub(r"`(.+?)`", r"\1", text)
    text = re.sub(r"\[(.+?)\]\([^)]+\)", r"\1", text)
    return text.encode("latin-1", "replace").decode("latin-1")


class _SignalPDF(FPDF):
    def header(self):
        if self.page_no() == 1:
            return
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*GOLD)
        self.cell(0, 6, "SIGNAL", align="L", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(*RULE)
        self.set_line_width(0.3)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_draw_color(*RULE)
        self.set_line_width(0.2)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.ln(2)
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*MUTED)
        self.cell(
            0, 4,
            "Generated by SIGNAL Research Agent - aniagent.streamlit.app",
            align="C", new_x="LMARGIN", new_y="NEXT",
        )
        self.cell(0, 4, f"Page {self.page_no()}/{{nb}}", align="C")


def _gen_time() -> str:
    return datetime.now(ZoneInfo("America/New_York")).strftime("%b %d %Y - %H:%M ET")


def memo_to_pdf(section_title: str, subtitle: str, body_markdown: str) -> bytes:
    pdf = _SignalPDF(format="Letter")
    pdf.set_auto_page_break(auto=True, margin=22)
    pdf.alias_nb_pages()
    pdf.set_margins(left=18, top=18, right=18)
    pdf.add_page()

    # ── Cover header ──
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(*GOLD)
    pdf.cell(0, 8, "SIGNAL", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(*MUTED)
    pdf.cell(
        0, 5,
        "ANI SINGH  -  PRIVATE RESEARCH AGENT",
        align="C", new_x="LMARGIN", new_y="NEXT",
    )
    pdf.ln(6)
    pdf.set_draw_color(*GOLD)
    pdf.set_line_width(0.4)
    pdf.line(pdf.l_margin + 40, pdf.get_y(), pdf.w - pdf.r_margin - 40, pdf.get_y())
    pdf.ln(8)

    # ── Section title ──
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(*GOLD)
    pdf.multi_cell(0, 7, _sanitize(section_title.upper()), align="C")
    if subtitle:
        pdf.ln(1)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*MUTED)
        pdf.multi_cell(0, 5, _sanitize(subtitle), align="C")
    pdf.ln(2)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(*MUTED)
    pdf.cell(0, 4, _gen_time(), align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)
    pdf.set_draw_color(*RULE)
    pdf.set_line_width(0.2)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    pdf.ln(6)

    # ── Body ──
    usable_w = pdf.w - pdf.l_margin - pdf.r_margin

    def mc(h: float, text: str) -> None:
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(w=usable_w, h=h, text=text)

    for raw in body_markdown.split("\n"):
        stripped = raw.strip()
        text = _sanitize(stripped)

        if not stripped:
            pdf.ln(2.5)
            continue

        if stripped.startswith("# "):
            pdf.ln(2)
            pdf.set_font("Helvetica", "B", 13)
            pdf.set_text_color(*GOLD)
            mc(7, _sanitize(stripped[2:]))
            pdf.ln(1)
        elif stripped.startswith("## "):
            pdf.ln(3)
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(*GOLD)
            mc(6, _sanitize(stripped[3:]))
            pdf.set_draw_color(*RULE)
            pdf.line(pdf.l_margin, pdf.get_y() + 0.5, pdf.w - pdf.r_margin, pdf.get_y() + 0.5)
            pdf.ln(2)
        elif stripped.startswith("### "):
            pdf.ln(2)
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*GOLD)
            mc(5, _sanitize(stripped[4:]))
            pdf.ln(1)
        elif stripped.startswith(("- ", "* ")):
            pdf.set_font("Times", "", 10)
            pdf.set_text_color(*DARK)
            mc(5, "   *  " + _sanitize(stripped[2:]))
        elif stripped == "---":
            pdf.ln(2)
            pdf.set_draw_color(*RULE)
            pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
            pdf.ln(3)
        else:
            pdf.set_font("Times", "", 10)
            pdf.set_text_color(*DARK)
            mc(5, text)

    out = pdf.output()
    if isinstance(out, str):
        out = out.encode("latin-1")
    return bytes(out)


def filename(section: str, suffix: str = "") -> str:
    date = datetime.now(ZoneInfo("America/New_York")).strftime("%Y%m%d")
    parts = ["SIGNAL", section]
    if suffix:
        slug = re.sub(r"[^A-Za-z0-9]+", "", suffix.title())
        if slug:
            parts.append(slug)
    parts.append(date)
    return "_".join(parts) + ".pdf"
